---
title: "reading_two_r_intro"
author: "Yi (Chris) Chen"
date: "October 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## reading two: R intro
### chapter two
```{r}
# vectors and assignments
x <- c(10.4,5.6,6.4,21.7)
assign('y',c(10.4,5.6,6.4,21.7))
c(10.4,5.6,6.4,21.7) -> z

all(x == y & x==z)
```

```{r}
# vector arithmetic
sort(x,decreasing = TRUE)
```

```{r}
# generating regular sequences
seq(2,10)
seq(from=10,to=2)
seq(-5,5,by=.2)
seq(length=50,from=-5,to=2)


rep(x,time=5)
rep(x,each=5)
```

```{r}
# character vectors
labs <- paste(c('x','y'),1:8,sep='')
labs
```

```{r}
c('x','y')[rep(c(1,2,2,1),times=4)]
```

### chapter three
```{r}
z <- rnorm(100)
attr(z,'dim') <- c(10,10)
```

### chapter 4
```{r}
state <- c('a','c','da','a','da','da','re','c','re','re','da','re','a','b','b','b','da')
state <- factor(state)
state
levels(state)

income <- 1:17
incmeans <- tapply(income,state,mean)
incmeans

ordered(state)
```

### chapter 5
```{r}
x <- array(1:20,dim=c(4,5))
x
y <- array(c(1:3,3:1),dim = c(3,2))
y

# outer product of two arrays
# outer ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

e <- 0:9 %o% 0:9
d <- outer(0:9,0:9,'*')
all(e==d)
fr <- table(outer(d,d,'-'))
plot(fr,xlab = 'determinant',ylab = 'frequency')


f <- function(x,y){cos(y)/(1+x^2)}
outer(1:9,1:9,f)

# generalize transpose of an array
A <- matrix(1:25,5,5)
b <- aperm(A,c(2,1))
c <- t(A)
all(b==c)

# matrix multiplication
A <- matrix(1:25,5,5)
B <- matrix(5:30,5,5)
A*B
A%*%B

all(crossprod(A,B) == t(A)%*%B)  # ?????????????????????????????????????????????????????????
diag(A)  # ??????????????????


# linear equation and inversion
A <- matrix(rnorm(5*5),5,5)
B <- solve(A)  # ????????????

```

```{r}
# Eigenvalues and eigenvectors, ??????????????????????????????
ev <- eigen(A)
evalue <- eigen(A)$values
evector <- eigen(A)$vectors
```

```{r}

```

