---
title: "ADA"
author: "Yi Chen(yc3356)"
date: "April 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ADA Final

```{r}
library(survival)
data <- survival::cancer

data <- na.omit(data)
status <- as.factor(data$status)
time <- data$time
data$sex[data$sex == 2] = 0
sex <- as.factor(data$sex)

km <- survfit(Surv(time,status)~1,data=data,type="kaplan-meier")
plot(km$time,km$surv, type="s",xlab="Time (day)",ylab="Survival",main="survival function",lwd=2,,cex.axis=1.5,cex.lab=1.5)
text(80,0.2,"One month")
text(410,0.2,"One year")
text(780,0.2,"two years")
abline(v=30, lty=2, lwd=2, col="red")
abline(v=365, lty=2, lwd=2, col="blue")
abline(v=730, lty=2, lwd=2, col="green")
```

```{r}
fit <- survfit(Surv(time,status)~sex,data=data)
plot(fit,lty=1:2,col=1:2,main = "Survival function plot for male patient and female patient",xlab = "time",ylab = "probability",lwd=2,,cex.axis=1.5,cex.lab=1.5)
legend("topright",legend= c("female","male"),lwd=2,lty=1:2,col=1:2,bty="n",ncol=2,cex=2,pt.cex=0.7)
```
```{r}
survdiff(Surv(time,status)~sex,data=data)
```


```{r}
fitphm <- coxph(Surv(time,status)~sex+ph.ecog+age+ph.karno+pat.karno+meal.cal+wt.loss,data=data)
fitreduced <- coxph(Surv(time,status)~sex+ph.ecog,data = data)
predict(fitreduced,sex=0,ph.ecog=0)

summary(fitphm)
summary(fitreduced)
anova(fitphm,fitreduced)
```
```{r}
fitphm <- coxph(Surv(time,status)~sex+ph.ecog,data=data)
summary(fitphm)
```

```{r}
install.packages("PerformanceAnalytics")
library("PerformanceAnalytics")

chart.Correlation(my_data, histogram=TRUE, pch=19)
```

