---
title: "homework three"
author: "Yi Chen(yc3356)"
date: "February 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## homework three
```{r}
setwd("C:/Users/cheny/Desktop/study/second term/Statistical Method In Finance/homework/homework three")
data <- read.csv("hw3.csv")
```

First, we calculate the daily log-return of these three stocks
```{r}
library(MASS)
library(quadprog)

price <- cbind(data$CAT_AC,data$IBM_AC,data$MSFT_AC)
n <- dim(price)[1]
return <- log(price[2:n,]/price[1:(n-1),])
mu <- colMeans(return)
sigma <- cov(return)
```

## problem (a)/(b)
```{r}
muP <- seq(0.0001,0.002,length.out = 400) # target portfolio return
sdP <- muP
weight <- matrix(1,nrow = 400,ncol = 3)

for (i in 1:length(muP)) # find the optimal portfolios
{
        result = solve.QP(Dmat=2*sigma,dvec=rep(0,3),
        Amat=cbind(rep(1,3),mu),bvec=c(1,muP[i]),meq=2)
        sdP[i] = sqrt(result$value)
        weight[i,] = result$solution
}
par(mfrow = c(1,1))
plot(sdP,muP,type="l",xlim=c(.01,.03),ylim=c(0,0.002),,lwd=3,col="red")

# efficient frontier
text(sqrt(sigma[1,1]),mu[1],"cat",cex=1.1)
text(sqrt(sigma[2,2]),mu[2],"IBM",cex=1.1)
text(sqrt(sigma[3,3]),mu[3],"MSFT",cex=1.1)

rf = .05/253 # riskfree rate
points(0,rf,cex=1.1,pch="x") # show riskfree asset
sharpe =(muP-rf)/sdP # Sharpe's ratios
ind3 = (sharpe == max(sharpe)) # find maximum Sharpe's ratio
lines(c(0,1),rf+c(0,1)*sharpe[ind3],lwd=2,lty=1,col="black") # line of optimal portfolios
points(sdP[ind3],muP[ind3],cex=1.1,pch="x") # show tangency portfolio
```

## problem (c)
```{r}
muP = seq(min(mu),max(mu),length=400) # target portfolio return
for (i in 1:length(muP)) # find the optimal portfolios
{
        result = solve.QP(Dmat=2*sigma,dvec=rep(0,3),Amat=cbind(rep(1,3),mu,diag(1,3)),bvec=c(1,muP[i],rep(0,3)),meq=2)
        sdP[i] = sqrt(result$value)
        weight[i,] = result$solution
}
par(mfrow = c(1,1))
plot(sdP,muP,type="l",xlim=c(.01,.03),ylim=c(0,.0015),lwd=3,col="blue") # efficient frontier
#lines(sdP,muP,type="l",xlim=c(0,.04),ylim=c(0,.001),lwd=3,col="blue") # efficient frontier
text(sqrt(sigma[1,1]),mu[1],"GM",cex=1.1)
text(sqrt(sigma[2,2]),mu[2],"Merck",cex=1.1)
text(sqrt(sigma[3,3]),mu[3],"Citi",cex=1.1)
```

